-- ============================================================
-- مخطط قاعدة بيانات "لوحة أداء التمارين" — Supabase / Postgres
-- شغّلي هذا الملف كاملًا مرة واحدة من: Supabase Dashboard → SQL Editor → New query
-- ============================================================

-- تفعيل الامتداد المطلوب لتوليد المعرّفات (موجود افتراضيًا في Supabase غالبًا)
create extension if not exists "pgcrypto";

-- ------------------------------------------------------------
-- 1) program_items: عناصر البرنامج الأسبوعي (كل تمرين داخل كل يوم)
-- ------------------------------------------------------------
create table if not exists program_items (
  id               bigint generated by default as identity primary key,
  day_name         text not null,
  day_order        int  not null,
  theme            text not null,
  is_rest          boolean not null default false,
  sort_order       int  not null default 0,
  name             text,
  muscle           text,
  type             text,
  sets             int,
  reps             int,
  unit             text,
  done             boolean not null default false,
  last_week_sets   int not null default 0,
  last_week_reps   int not null default 0,
  this_week_sets   int,
  this_week_reps   int,
  created_at       timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 2) alternatives: البدائل الذكية لكل تمرين (أساسية/متقدمة) + ما تم تنفيذه لكل بديل
-- ------------------------------------------------------------
create table if not exists alternatives (
  id               bigint generated by default as identity primary key,
  program_item_id  bigint not null references program_items(id) on delete cascade,
  name             text not null,
  tier             text not null default 'basic', -- 'basic' | 'advanced'
  active           boolean not null default false,
  sets             int,
  reps             int
);

-- ------------------------------------------------------------
-- 3) catalog_exercises: كتالوج مرجعي لتصفح كل التمارين (تبويب "جدول التمارين")
-- ------------------------------------------------------------
create table if not exists catalog_exercises (
  id            bigint primary key,
  muscle        text not null,
  name          text not null,
  type          text not null,
  weekly_goal   int  not null,
  monthly_goal  int  not null,
  yearly_goal   int  not null
);

-- ------------------------------------------------------------
-- 4) progress_accum: تراكم الإنجاز الشهري/السنوي (صف واحد فقط)
-- ------------------------------------------------------------
create table if not exists progress_accum (
  id                 int primary key default 1,
  month_done         int not null default 0,
  month_goal         int not null default 0,
  year_done          int not null default 0,
  year_goal          int not null default 0,
  weeks_into_month   int not null default 0,
  constraint single_row check (id = 1)
);

insert into progress_accum (id) values (1)
  on conflict (id) do nothing;

-- ============================================================
-- Row Level Security
-- التطبيق مصمم كمتعقّب شخصي بدون نظام حسابات (auth) لتبسيط الإعداد.
-- السياسات التالية تسمح لأي شخص يملك مفتاح anon (المفتاح العام في js/config.js)
-- بالقراءة والكتابة الكاملة. هذا مناسب لمتعقب شخصي لا يحتوي بيانات حساسة،
-- لكن أي شخص يعرف رابط مشروعك ومفتاحه سيقدر يعدّل بياناتك.
-- إن أردتِ حماية أقوى لاحقًا: فعّلي Supabase Auth واربطي كل صف بـ user_id،
-- ثم استبدلي "using (true)" بشرط "using (auth.uid() = user_id)".
-- ============================================================

alter table program_items    enable row level security;
alter table alternatives     enable row level security;
alter table catalog_exercises enable row level security;
alter table progress_accum   enable row level security;

create policy "anon full access - program_items"
  on program_items for all
  using (true) with check (true);

create policy "anon full access - alternatives"
  on alternatives for all
  using (true) with check (true);

create policy "anon read - catalog_exercises"
  on catalog_exercises for select
  using (true);

create policy "anon full access - progress_accum"
  on progress_accum for all
  using (true) with check (true);

-- ============================================================
-- بيانات أولية (Seed) — البرنامج الأسبوعي الافتراضي، الأداء يبدأ من صفر
-- الأسبوع يبدأ من الخميس (ظهر وبايسبس) بحسب طلبك
-- ============================================================

-- اليوم 1: الخميس — ظهر وبايسبس (day_order = 1)
insert into program_items (day_name, day_order, theme, is_rest, sort_order, name, muscle, type, sets, reps, unit) values
('الخميس', 1, 'ظهر وبايسبس', false, 1, 'سحب أمامي', 'الظهر', 'تقوية', 4, 10, 'تكرار'),
('الخميس', 1, 'ظهر وبايسبس', false, 2, 'ديدلفت', 'الظهر', 'تقوية', 3, 8, 'تكرار'),
('الخميس', 1, 'ظهر وبايسبس', false, 3, 'تجديف بار', 'الظهر', 'تقوية', 3, 12, 'تكرار'),
('الخميس', 1, 'ظهر وبايسبس', false, 4, 'كرل بار', 'البايسبس', 'تقوية', 3, 12, 'تكرار'),
('الخميس', 1, 'ظهر وبايسبس', false, 5, 'كرل تركيز', 'البايسبس', 'تقوية', 3, 12, 'تكرار'),
('الخميس', 1, 'ظهر وبايسبس', false, 6, 'إطالة الظهر (وضعية الطفل)', 'الظهر', 'إطالة', 3, 45, 'ثانية');

-- اليوم 2: الجمعة — أرجل كاملة (day_order = 2)
insert into program_items (day_name, day_order, theme, is_rest, sort_order, name, muscle, type, sets, reps, unit) values
('الجمعة', 2, 'أرجل كاملة', false, 1, 'سكوات', 'الأرجل', 'تقوية', 4, 10, 'تكرار'),
('الجمعة', 2, 'أرجل كاملة', false, 2, 'لنجز', 'الأرجل', 'تقوية', 3, 12, 'تكرار'),
('الجمعة', 2, 'أرجل كاملة', false, 3, 'ضغط أرجل', 'الأرجل', 'تقوية', 3, 15, 'تكرار'),
('الجمعة', 2, 'أرجل كاملة', false, 4, 'إطالة العضلة الخلفية للفخذ', 'الأرجل', 'إطالة', 3, 30, 'ثانية');

-- اليوم 3: السبت — راحة نشطة (day_order = 3)
insert into program_items (day_name, day_order, theme, is_rest, sort_order, name, muscle, type, sets, reps, unit) values
('السبت', 3, 'راحة نشطة', true, 1, null, null, null, null, null, null);

-- اليوم 4: الأحد — صدر وترايسبس (day_order = 4)
insert into program_items (day_name, day_order, theme, is_rest, sort_order, name, muscle, type, sets, reps, unit) values
('الأحد', 4, 'صدر وترايسبس', false, 1, 'ضغط بار مسطح', 'الصدر', 'تقوية', 4, 10, 'تكرار'),
('الأحد', 4, 'صدر وترايسبس', false, 2, 'ضغط دمبل مائل', 'الصدر', 'تقوية', 3, 12, 'تكرار'),
('الأحد', 4, 'صدر وترايسبس', false, 3, 'تفتيح صدر بالكيبل', 'الصدر', 'تقوية', 3, 15, 'تكرار'),
('الأحد', 4, 'صدر وترايسبس', false, 4, 'ضغط فرنسي', 'الترايسبس', 'تقوية', 3, 12, 'تكرار'),
('الأحد', 4, 'صدر وترايسبس', false, 5, 'بوش داون كيبل', 'الترايسبس', 'تقوية', 3, 15, 'تكرار'),
('الأحد', 4, 'صدر وترايسبس', false, 6, 'إطالة الصدر على الحائط', 'الصدر', 'إطالة', 3, 30, 'ثانية');

-- اليوم 5: الاثنين — أكتاف وبطن (day_order = 5)
insert into program_items (day_name, day_order, theme, is_rest, sort_order, name, muscle, type, sets, reps, unit) values
('الاثنين', 5, 'أكتاف وبطن', false, 1, 'ضغط أكتاف بالدمبل', 'الأكتاف', 'تقوية', 4, 10, 'تكرار'),
('الاثنين', 5, 'أكتاف وبطن', false, 2, 'رفرفة جانبية', 'الأكتاف', 'تقوية', 3, 15, 'تكرار'),
('الاثنين', 5, 'أكتاف وبطن', false, 3, 'سحب بار للأمام', 'الأكتاف', 'تقوية', 3, 12, 'تكرار'),
('الاثنين', 5, 'أكتاف وبطن', false, 4, 'كرانش', 'البطن', 'تقوية', 4, 20, 'تكرار'),
('الاثنين', 5, 'أكتاف وبطن', false, 5, 'بلانك', 'البطن', 'تقوية', 3, 45, 'ثانية'),
('الاثنين', 5, 'أكتاف وبطن', false, 6, 'إطالة الكتف الخلفي', 'الأكتاف', 'إطالة', 3, 30, 'ثانية');

-- اليوم 6: الثلاثاء — كارديو وإطالة شاملة (day_order = 6)
insert into program_items (day_name, day_order, theme, is_rest, sort_order, name, muscle, type, sets, reps, unit) values
('الثلاثاء', 6, 'كارديو وإطالة شاملة', false, 1, 'إطالة قبل التدريب', 'الكارديو', 'إطالة', 1, 5, 'دقيقة'),
('الثلاثاء', 6, 'كارديو وإطالة شاملة', false, 2, 'جري', 'الكارديو', 'كارديو', 1, 25, 'دقيقة'),
('الثلاثاء', 6, 'كارديو وإطالة شاملة', false, 3, 'نط الحبل', 'الكارديو', 'كارديو', 3, 2, 'دقيقة'),
('الثلاثاء', 6, 'كارديو وإطالة شاملة', false, 4, 'إطالة عامة بعد الكارديو', 'الكارديو', 'إطالة', 1, 10, 'دقيقة'),
('الثلاثاء', 6, 'كارديو وإطالة شاملة', false, 5, 'إطالة عضلات البطن (كوبرا)', 'البطن', 'إطالة', 3, 30, 'ثانية');

-- اليوم 7: الأربعاء — راحة كاملة (day_order = 7)
insert into program_items (day_name, day_order, theme, is_rest, sort_order, name, muscle, type, sets, reps, unit) values
('الأربعاء', 7, 'راحة كاملة', true, 1, null, null, null, null, null, null);

-- البدائل الذكية — مرتبطة بالتمارين الأربعة في يوم الخميس (ظهر وبايسبس)
insert into alternatives (program_item_id, name, tier)
select id, alt.name, alt.tier
from program_items,
lateral (values
  ('Reverse Hyperextension', 'basic'),
  ('Single-Leg Glute Bridge', 'basic'),
  ('Nordic Hamstring Curl', 'basic'),
  ('Superman', 'basic'),
  ('Front Lever', 'advanced'),
  ('Back Extension', 'advanced')
) as alt(name, tier)
where program_items.name = 'ديدلفت';

insert into alternatives (program_item_id, name, tier)
select id, alt.name, 'basic'
from program_items,
lateral (values ('Inverted Row (Australian Pull-up)'), ('Front Lever Row'), ('Rings Row')) as alt(name)
where program_items.name = 'تجديف بار';

insert into alternatives (program_item_id, name, tier)
select id, alt.name, 'basic'
from program_items,
lateral (values ('Chin-up'), ('Ring Biceps Curl'), ('Towel Curl')) as alt(name)
where program_items.name = 'كرل بار';

insert into alternatives (program_item_id, name, tier)
select id, alt.name, 'basic'
from program_items,
lateral (values ('Chin-up'), ('Ring Biceps Curl'), ('Towel Curl')) as alt(name)
where program_items.name = 'كرل تركيز';

-- كتالوج التمارين المرجعي (٣٠ تمرينًا عبر كل الأعضاء)
insert into catalog_exercises (id, muscle, name, type, weekly_goal, monthly_goal, yearly_goal) values
(1,  'الصدر',    'ضغط بار مسطح',                  'تقوية', 3, 12, 156),
(2,  'الصدر',    'ضغط دمبل مائل',                 'تقوية', 3, 12, 156),
(3,  'الصدر',    'تفتيح صدر بالكيبل',              'تقوية', 2, 8,  104),
(4,  'الصدر',    'إطالة الصدر على الحائط',         'إطالة', 4, 16, 208),
(5,  'الظهر',    'سحب أمامي',                     'تقوية', 3, 12, 156),
(6,  'الظهر',    'ديدلفت',                        'تقوية', 2, 8,  104),
(7,  'الظهر',    'تجديف بار',                     'تقوية', 3, 12, 156),
(8,  'الظهر',    'إطالة الظهر (وضعية الطفل)',      'إطالة', 5, 20, 260),
(9,  'الأرجل',   'سكوات',                         'تقوية', 3, 12, 156),
(10, 'الأرجل',   'لنجز',                          'تقوية', 3, 12, 156),
(11, 'الأرجل',   'ضغط أرجل',                      'تقوية', 2, 8,  104),
(12, 'الأرجل',   'إطالة العضلة الخلفية للفخذ',      'إطالة', 4, 16, 208),
(13, 'الأكتاف',  'ضغط أكتاف بالدمبل',              'تقوية', 3, 12, 156),
(14, 'الأكتاف',  'رفرفة جانبية',                  'تقوية', 3, 12, 156),
(15, 'الأكتاف',  'سحب بار للأمام',                 'تقوية', 2, 8,  104),
(16, 'الأكتاف',  'إطالة الكتف الخلفي',              'إطالة', 4, 16, 208),
(17, 'البايسبس', 'كرل بار',                       'تقوية', 3, 12, 156),
(18, 'البايسبس', 'كرل تركيز',                     'تقوية', 2, 8,  104),
(19, 'البايسبس', 'إطالة العضلة ذات الرأسين',        'إطالة', 4, 16, 208),
(20, 'الترايسبس','ضغط فرنسي',                     'تقوية', 3, 12, 156),
(21, 'الترايسبس','بوش داون كيبل',                  'تقوية', 3, 12, 156),
(22, 'الترايسبس','إطالة الترايسبس خلف الرأس',       'إطالة', 4, 16, 208),
(23, 'البطن',    'كرانش',                         'تقوية', 4, 16, 208),
(24, 'البطن',    'بلانك',                         'تقوية', 5, 20, 260),
(25, 'البطن',    'رفع أرجل معلق',                  'تقوية', 3, 12, 156),
(26, 'البطن',    'إطالة عضلات البطن (كوبرا)',       'إطالة', 4, 16, 208),
(27, 'الكارديو', 'جري',                           'كارديو',4, 16, 208),
(28, 'الكارديو', 'دراجة ثابتة',                    'كارديو',3, 12, 156),
(29, 'الكارديو', 'نط الحبل',                      'كارديو',3, 12, 156),
(30, 'الكارديو', 'إطالة عامة بعد الكارديو',         'إطالة', 5, 20, 260),
(31, 'الكارديو', 'إطالة قبل التدريب',               'إطالة', 1, 4,  52)
on conflict (id) do nothing;
